// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProdavnicaSlatkisa.API.Db;

#nullable disable

namespace ProdavnicaSlatkisa.API.Migrations
{
    [DbContext(typeof(CustomDbContext))]
    partial class CustomDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProdavnicaSlatkisa.API.Db.TblAdministrator", b =>
                {
                    b.Property<int>("AdminId")
                        .HasColumnType("int")
                        .HasColumnName("AdminID");

                    b.Property<string>("Jmbg")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)")
                        .HasColumnName("JMBG");

                    b.Property<string>("Lozinka")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("AdminId")
                        .HasName("PK__tblAdmin__719FE4E8D4711B74");

                    b.ToTable("tblAdministrator", (string)null);
                });

            modelBuilder.Entity("ProdavnicaSlatkisa.API.Db.TblKorisnik", b =>
                {
                    b.Property<int>("KorisnikId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("KorisnikID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KorisnikId"));

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Grad")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Ime")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Kontakt")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Prezime")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("KorisnikId")
                        .HasName("PK__tblKoris__80B06D61899A89DC");

                    b.ToTable("tblKorisnik", (string)null);
                });

            modelBuilder.Entity("ProdavnicaSlatkisa.API.Db.TblKorpa", b =>
                {
                    b.Property<int>("KorpaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("KorpaID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KorpaId"));

                    b.Property<int?>("BrProizvoda")
                        .HasColumnType("int");

                    b.Property<int>("KorisnikId")
                        .HasColumnType("int")
                        .HasColumnName("KorisnikID");

                    b.Property<int?>("UkupanIznos")
                        .HasColumnType("int");

                    b.HasKey("KorpaId")
                        .HasName("PK__tblKorpa__C298DFB3144710A7");

                    b.HasIndex("KorisnikId");

                    b.ToTable("tblKorpa", (string)null);
                });

            modelBuilder.Entity("ProdavnicaSlatkisa.API.Db.TblKupac", b =>
                {
                    b.Property<int>("KupacId")
                        .HasColumnType("int")
                        .HasColumnName("KupacID");

                    b.Property<int?>("BrojKupovina")
                        .HasColumnType("int");

                    b.Property<string>("LozinkaRk")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool?>("Registrovan")
                        .HasColumnType("bit");

                    b.Property<string>("UsernameRk")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("UsernameRK");

                    b.HasKey("KupacId")
                        .HasName("PK__tblKupac__A9593C7BFBB58D51");

                    b.ToTable("tblKupac", (string)null);
                });

            modelBuilder.Entity("ProdavnicaSlatkisa.API.Db.TblModel", b =>
                {
                    b.Property<int>("Idmodela")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDModela");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idmodela"));

                    b.Property<string>("NazivModela")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Idmodela")
                        .HasName("PK__tblModel__A33B9CC03447082F");

                    b.ToTable("tblModel", (string)null);
                });

            modelBuilder.Entity("ProdavnicaSlatkisa.API.Db.TblProizvod", b =>
                {
                    b.Property<int>("IdProizvoda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDProizvod");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProizvoda"));

                    b.Property<decimal>("Cena")
                        .HasColumnType("numeric(10, 2)");

                    b.Property<int>("Idmodela")
                        .HasColumnType("int")
                        .HasColumnName("IDModela");

                    b.Property<int>("Idproizvodjaca")
                        .HasColumnType("int")
                        .HasColumnName("IDProizvodjaca");

                    b.Property<int>("KolicinaNaStanju")
                        .HasColumnType("int");

                    b.Property<int>("TipProizvodaId")
                        .HasColumnType("int")
                        .HasColumnName("TipProizvodaID");

                    b.HasKey("IdProizvoda")
                        .HasName("PK__tblProiz__B01F3D4D56DD1E77");

                    b.HasIndex("Idmodela");

                    b.HasIndex("Idproizvodjaca");

                    b.HasIndex("TipProizvodaId");

                    b.ToTable("tblProizvod", (string)null);
                });

            modelBuilder.Entity("ProdavnicaSlatkisa.API.Db.TblProizvodUkorpi", b =>
                {
                    b.Property<int>("ProizUkorpiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ProizUKorpiID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProizUkorpiId"));

                    b.Property<int>("BrojKomada")
                        .HasColumnType("int");

                    b.Property<int>("Iznos")
                        .HasColumnType("int");

                    b.Property<int>("KorpaId")
                        .HasColumnType("int")
                        .HasColumnName("KorpaID");

                    b.Property<int>("ProizvodId")
                        .HasColumnType("int")
                        .HasColumnName("IDProizvod");

                    b.HasKey("ProizUkorpiId")
                        .HasName("PK__tblProiz__8780F10959FA40CC");

                    b.HasIndex("KorpaId");

                    b.HasIndex("ProizvodId");

                    b.ToTable("tblProizvodUKorpi", null, t =>
                        {
                            t.HasTrigger("brisanjeKorpeIVracanjeProizvodTriger");

                            t.HasTrigger("trg_AddProizvodToKorpa");
                        });
                });

            modelBuilder.Entity("ProdavnicaSlatkisa.API.Db.TblProizvodjac", b =>
                {
                    b.Property<int>("Idproizvodjaca")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDProizvodjaca");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idproizvodjaca"));

                    b.Property<string>("NazivProizvodjaca")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ZemljaPorekla")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Idproizvodjaca")
                        .HasName("PK__tblProiz__4ABF484F14EEABBC");

                    b.ToTable("tblProizvodjac", (string)null);
                });

            modelBuilder.Entity("ProdavnicaSlatkisa.API.Db.TblRacun", b =>
                {
                    b.Property<int>("RacunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RacunID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RacunId"));

                    b.Property<string>("ClientSecret")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("DatumKupovine")
                        .HasColumnType("date");

                    b.Property<int?>("IznosSaPopustom")
                        .HasColumnType("int");

                    b.Property<int>("KorpaId")
                        .HasColumnType("int")
                        .HasColumnName("KorpaID");

                    b.Property<string>("PaymentIntentId")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<bool?>("Popust")
                        .HasColumnType("bit");

                    b.Property<int?>("ProcenatPop")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("UkupanIznos")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("VremeKupovine")
                        .HasColumnType("time");

                    b.HasKey("RacunId")
                        .HasName("PK__tblRacun__07B8F7ACCB50282D");

                    b.HasIndex("KorpaId");

                    b.ToTable("tblRacun", (string)null);
                });

            modelBuilder.Entity("ProdavnicaSlatkisa.API.Db.TblTipProizvodum", b =>
                {
                    b.Property<int>("TipProizvodaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TipProizvodaID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipProizvodaId"));

                    b.Property<string>("Sastav")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TipProizvodaId")
                        .HasName("PK__tblTipPr__2A3E562CEE5424F0");

                    b.ToTable("tblTipProizvoda", (string)null);
                });

            modelBuilder.Entity("ProdavnicaSlatkisa.API.Db.TblAdministrator", b =>
                {
                    b.HasOne("ProdavnicaSlatkisa.API.Db.TblKorisnik", "Korisnik")
                        .WithOne("TblAdministrator")
                        .HasForeignKey("ProdavnicaSlatkisa.API.Db.TblAdministrator", "AdminId")
                        .IsRequired()
                        .HasConstraintName("FK_Administrator_Korisnik");

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("ProdavnicaSlatkisa.API.Db.TblKorpa", b =>
                {
                    b.HasOne("ProdavnicaSlatkisa.API.Db.TblKorisnik", "Korisnik")
                        .WithMany("TblKorpas")
                        .HasForeignKey("KorisnikId")
                        .IsRequired()
                        .HasConstraintName("FK_Korpa_Korisnik");

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("ProdavnicaSlatkisa.API.Db.TblKupac", b =>
                {
                    b.HasOne("ProdavnicaSlatkisa.API.Db.TblKorisnik", "Korisnik")
                        .WithOne("TblKupac")
                        .HasForeignKey("ProdavnicaSlatkisa.API.Db.TblKupac", "KupacId")
                        .IsRequired()
                        .HasConstraintName("FK_Kupac_Korisnik");

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("ProdavnicaSlatkisa.API.Db.TblProizvod", b =>
                {
                    b.HasOne("ProdavnicaSlatkisa.API.Db.TblModel", "IdmodelaNavigation")
                        .WithMany("TblProizvodi")
                        .HasForeignKey("Idmodela")
                        .IsRequired()
                        .HasConstraintName("FK_Proizvod_Model");

                    b.HasOne("ProdavnicaSlatkisa.API.Db.TblProizvodjac", "IdproizvodjacaNavigation")
                        .WithMany("TblProizvod")
                        .HasForeignKey("Idproizvodjaca")
                        .IsRequired()
                        .HasConstraintName("FK_Proizvod_Proizvodjac");

                    b.HasOne("ProdavnicaSlatkisa.API.Db.TblTipProizvodum", "TipProizvoda")
                        .WithMany("TblProizvodi")
                        .HasForeignKey("TipProizvodaId")
                        .IsRequired()
                        .HasConstraintName("FK_Proizvod_TipProizvoda");

                    b.Navigation("IdmodelaNavigation");

                    b.Navigation("IdproizvodjacaNavigation");

                    b.Navigation("TipProizvoda");
                });

            modelBuilder.Entity("ProdavnicaSlatkisa.API.Db.TblProizvodUkorpi", b =>
                {
                    b.HasOne("ProdavnicaSlatkisa.API.Db.TblKorpa", "Korpa")
                        .WithMany("TblProizvodUkorpis")
                        .HasForeignKey("KorpaId")
                        .IsRequired()
                        .HasConstraintName("FK_ProizvodUKorpi_Korpa");

                    b.HasOne("ProdavnicaSlatkisa.API.Db.TblProizvod", "ProizvodNavigation")
                        .WithMany("TblProizvodUkorpis")
                        .HasForeignKey("ProizvodId")
                        .IsRequired()
                        .HasConstraintName("FK_ProizvodUKorpi_Proizvod");

                    b.Navigation("Korpa");

                    b.Navigation("ProizvodNavigation");
                });

            modelBuilder.Entity("ProdavnicaSlatkisa.API.Db.TblRacun", b =>
                {
                    b.HasOne("ProdavnicaSlatkisa.API.Db.TblKorpa", "Korpa")
                        .WithMany("TblRacuns")
                        .HasForeignKey("KorpaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Racun_Korpa");

                    b.Navigation("Korpa");
                });

            modelBuilder.Entity("ProdavnicaSlatkisa.API.Db.TblKorisnik", b =>
                {
                    b.Navigation("TblAdministrator");

                    b.Navigation("TblKorpas");

                    b.Navigation("TblKupac");
                });

            modelBuilder.Entity("ProdavnicaSlatkisa.API.Db.TblKorpa", b =>
                {
                    b.Navigation("TblProizvodUkorpis");

                    b.Navigation("TblRacuns");
                });

            modelBuilder.Entity("ProdavnicaSlatkisa.API.Db.TblModel", b =>
                {
                    b.Navigation("TblProizvodi");
                });

            modelBuilder.Entity("ProdavnicaSlatkisa.API.Db.TblProizvod", b =>
                {
                    b.Navigation("TblProizvodUkorpis");
                });

            modelBuilder.Entity("ProdavnicaSlatkisa.API.Db.TblProizvodjac", b =>
                {
                    b.Navigation("TblProizvod");
                });

            modelBuilder.Entity("ProdavnicaSlatkisa.API.Db.TblTipProizvodum", b =>
                {
                    b.Navigation("TblProizvodi");
                });
#pragma warning restore 612, 618
        }
    }
}
